### ISSUE TITLE
Trying to make this work on windows, keep getting assertion error:

### ISSUE THREAD

**Issue by vertgo** [keunwoochoi/LSTMetallica#9]
I already finished all the training and got this when I tried to output midi files

Traceback (most recent call last):
  File ".\main_post_process.py", line 127, in <module>
    conv_text_to_midi(result_dir + '/' + filename)
  File ".\main_post_process.py", line 115, in conv_text_to_midi
    midi.write_midifile(filename[:-4]+'.mid', pattern)
  File "C:\Program Files\Python35\lib\site-packages\midi\fileio.py", line 169, in write_midifile
    return write_midifile(out,pattern)
  File "C:\Program Files\Python35\lib\site-packages\midi\fileio.py", line 171, in write_midifile
    return writer.write(pattern)
  File "C:\Program Files\Python35\lib\site-packages\midi\fileio.py", line 105, in write
    self.write_track(track)
  File "C:\Program Files\Python35\lib\site-packages\midi\fileio.py", line 122, in write_track
    buf.extend(self.encode_midi_event(event))
  File "C:\Program Files\Python35\lib\site-packages\midi\fileio.py", line 141, in encode_midi_event
    assert isinstance(event.tick,int), event.tick
AssertionError: 0.0

**Comment by keunwoochoi** [comment]
Hi, I'd like to help but at the moment I can't afford time to investigate the problem. Sorry about it.

**Comment by sankexin** [comment]
> I already finished all the training and got this when I tried to output midi files
> 
> Traceback (most recent call last):
> File ".\main_post_process.py", line 127, in
> conv_text_to_midi(result_dir + '/' + filename)
> File ".\main_post_process.py", line 115, in conv_text_to_midi
> midi.write_midifile(filename[:-4]+'.mid', pattern)
> File "C:\Program Files\Python35\lib\site-packages\midi\fileio.py", line 169, in write_midifile
> return write_midifile(out,pattern)
> File "C:\Program Files\Python35\lib\site-packages\midi\fileio.py", line 171, in write_midifile
> return writer.write(pattern)
> File "C:\Program Files\Python35\lib\site-packages\midi\fileio.py", line 105, in write
> self.write_track(track)
> File "C:\Program Files\Python35\lib\site-packages\midi\fileio.py", line 122, in write_track
> buf.extend(self.encode_midi_event(event))
> File "C:\Program Files\Python35\lib\site-packages\midi\fileio.py", line 141, in encode_midi_event
> assert isinstance(event.tick,int), event.tick
> AssertionError: 0.0

you can: int(tick)
